# Generated by Django 5.1.4 on 2024-12-13 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_request'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Request',
        ),
    ]
