# Generated by Django 5.1.4 on 2024-12-14 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='completed_requests',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='request',
            name='pending_requests',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='request',
            name='position',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='total_requests',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='request',
            name='training_program',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
