# Generated by Django 5.1.4 on 2024-12-13 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_coursefeedback'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='coursefeedback',
            unique_together={('course', 'employee')},
        ),
    ]
