# Generated by Django 5.1.4 on 2024-12-15 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_request_completed_requests_request_pending_requests_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
        migrations.AlterModelOptions(
            name='courseassignment',
            options={'verbose_name': 'Course Assignment', 'verbose_name_plural': 'Course Assignments'},
        ),
        migrations.AlterModelOptions(
            name='coursefeedback',
            options={'verbose_name': 'Course Feedback', 'verbose_name_plural': 'Course Feedbacks'},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['order'], 'verbose_name': 'Module', 'verbose_name_plural': 'Modules'},
        ),
        migrations.AlterModelOptions(
            name='moduleprogress',
            options={'verbose_name': 'Module Progress', 'verbose_name_plural': 'Module Progresses'},
        ),
        migrations.AlterModelOptions(
            name='request',
            options={'verbose_name': 'Training Request', 'verbose_name_plural': 'Training Requests'},
        ),
        migrations.AlterField(
            model_name='request',
            name='duration',
            field=models.IntegerField(help_text='Duration in days'),
        ),
        migrations.AlterUniqueTogether(
            name='courseassignment',
            unique_together={('course', 'employee')},
        ),
        migrations.AlterUniqueTogether(
            name='moduleprogress',
            unique_together={('module', 'employee')},
        ),
    ]
