# Generated by Django 5.1.4 on 2024-12-15 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_course_options_alter_courseassignment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={},
        ),
        migrations.AlterModelOptions(
            name='courseassignment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='coursefeedback',
            options={},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={},
        ),
        migrations.AlterModelOptions(
            name='moduleprogress',
            options={},
        ),
        migrations.AlterModelOptions(
            name='request',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='courseassignment',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='moduleprogress',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='request',
            name='duration',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.course')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
